### ISSUE TITLE
Cannot read property 'MysqlConnection' of null

### ISSUE THREAD

**Issue by feelinc** [Sannis/node-mysql-libmysqlclient#162]
I'm using:
- Mountain lion
- Node v0.8.8
- node-mysql-libmysqlclient v1.5.1

log:

MysqlConnectionQueued.prototype = new bindings.MysqlConnection();
                                              ^
TypeError: Cannot read property 'MysqlConnection' of null
    at Object.<anonymous> (/Users/Me/Sites/app/node_modules/mysql-libmysqlclient/lib/mysql-libmysqlclient.js:208:47)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/Me/Sites/app/node_modules/mysql-libmysqlclient/doc/examples.js:14:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)

do you think the error related to missing mysql_bindings?

**Comment by whoughton** [comment]
I'm seeing this issue as well, with no solution found.
