### ISSUE TITLE
Can't install 'mysql.h' file not found

### ISSUE THREAD

**Issue by phoomin2012** [Sannis/node-mysql-libmysqlclient#193]
I can't install this module. NPM say

```
> mysql-libmysqlclient@1.6.0 install /Applications/XAMPP/xamppfiles/htdocs/travian5/server/node_modules/mysql-libmysqlclient
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/mysql_bindings/src/mysql_bindings.o
In file included from ../src/mysql_bindings.cc:17:
../src/./mysql_bindings_connection.h:11:10: fatal error: 'mysql.h' file not
      found
#include <mysql.h>
         ^
1 error generated.
make: *** [Release/obj.target/mysql_bindings/src/mysql_bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/XAMPP/xamppfiles/htdocs/travian5/server/node_modules/mysql-libmysqlclient
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mysql-libmysqlclient" "--save"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! mysql-libmysqlclient@1.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mysql-libmysqlclient@1.6.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mysql-libmysqlclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mysql-libmysqlclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mysql-libmysqlclient
npm ERR! There is likely additional logging output above.
```

**Comment by Sannis** [comment]
@phoomin2012 please specify your OSX/Xcode/clang versions and `mysql_config` without options output from terminal.
