### ISSUE TITLE
Cannot read property of null

### ISSUE THREAD

**Issue by notvishwanth** [Sannis/node-mysql-libmysqlclient#195]
i have
python 2.7
node 6.9.2
npm 3.10.9

when i try to run your sample files from tests/low-level-sync 
node setup-low-level-sync.js,
I'm getting cannot read property 'mysqlConnection' of null
```
MysqlConnectionQueued.prototype = new bindings.MysqlConnection();
                                             `` ^

TypeError: Cannot read property 'MysqlConnection' of null
    at Object.<anonymous> (C:\project\nodejs samp\node_modules\libmysqlclient\lib\mysql-libmysqlclient.js:220:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\project\nodejs samp\node_modules\libmysqlclient\tests\config.js:21:25)
    at Module._compile (module.js:570:32)
```

I've extracted the zip file and did the following
npm install
npm isntall node-gyp -g

but still the same problem persists, please help

**Comment by abhisekdg** [comment]
Node Version - 6.10.2 ( Previously working fine with v0.10.26)
NPM version - 3.10.10
OS - MacOS Sierra 10.12.4

@https://travis-ci.org/Sannis/node-mysql-libmysqlclient/jobs/194103714

var mysqllibclient = require('mysql-libmysqlclient'); ( 1.5.2)

After upgrading the node version to latest, it started throwing error.

**MysqlConnectionQueued.prototype = new bindings.MysqlConnection();
TypeError: Cannot read property 'MysqlConnection' of null**

Please can anyone suggest how it be supported in latest version of node ??
